service: antalmanac-backend

# Create an optimized package for our functions
#package:
#  individually: true

plugins:
  - serverless-offline
  - serverless-domain-manager
#  - serverless-dotenv-plugin # Load .env as environment variables

custom:
  serverless-offline:
    httpPort: 8080

  customDomain:
    domainName: api.antalmanacdev.de
    certificateName: '*.antalmanacdev.de'
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-1

functions:
    app:
      handler: server.handler
      events:
        - http:
            path: /{proxy+}
            method: ANY
            cors: true